#! /bin/sh
compton -b  # enable compositing

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_by_distance       true
bspc config focus_follows_pointer   true

# Start with two desktops on each monitor
bspc monitor -d 1 2
bspc monitor ^2 -d 1 2

bspc rule -a mplayer2 floating=on
bspc rule -a arandr floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

wmname LG3D
~/.lemonbar/panel & # start panel
sxhkd &
