#!/bin/bash

#Find the current directory & source utilities and config
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. $DIR/profile

if [ -z ${1+x} ]
then
    str=`amixer -M sget Master,0`
else
    str=`amixer -M set Master,0 $1`
    if [ "$1" != "toggle" ]
    then
        aplay -q "$DIR/bell.wav" &
    fi
fi

getVol() {
    local amixerStr=$1
    local trimFront=${amixerStr#*[}
    local nextBracketPos=`expr index "$trimFront" [`

    if [ ${trimFront:$nextBracketPos:3} == "off" ]
    then
        echo "M"
    else
        echo ${trimFront%%%]*}
    fi
}

volStr=`getVol "$str"`

echo "V$volStr" > "$PANEL_FIFO"
