#!/bin/bash

#Find the current directory & source utilities and config
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
. $DIR/profile

if [ -z ${1+x} ]
then
    str=`amixer -M sget Master,0`
else
    str=`amixer -M set Master,0 $1`
    if [ "$1" != "toggle" ]
    then
        aplay -q "$DIR/bell.wav" &
    fi
fi

str1=${str#Simple*[}
v1=${str1%%]*]}
il=`expr index "$str1" [`
o="off"
mutel=''
if [ ${str1:$il:3} == $o ]; then mutel='M'; fi
s=${str1:0:1}
str2=${str1#${str1:0:1}*[}
str1=$str2
str2=${str1#${str1:0:1}*[}
ir=`expr index "$str2" [`
muter=''
if [ ${str2:0:3} = $o ]; then muter='[M]'; fi
v2=${str2%\]}
v=${v1}\ $muter
echo "V$v" > "$PANEL_FIFO"
